/**
 * Salary & Wage Accounting - Google Sheets template.
 *
 * Generated by tools/appsscript.py from the module field reference.
 * Edit the SKILL.md, not this file: the next run would overwrite your change.
 *
 * How to use
 *   1. Extensions > Apps Script, in the spreadsheet you want to build into.
 *   2. Paste this file over anything in the editor and save.
 *   3. Run buildIntoActive from the editor once, or use the "Build template"
 *      menu that appears on the sheet. main() creates a new spreadsheet
 *      instead, if you would rather not bind this script to one.
 *
 * Rebuilding clears the generated tabs and rewrites them, so it is safe to
 * run again after changing the spec. Real rows you have typed into the data
 * tab are kept; only the template structure is rewritten.
 */
var CONFIG = {
    "title": "Salary & Wage Accounting",
    "tier": "Growth",
    "layer": "Layer 5: Expense & Payroll",
    "fields": [
      {
        "name": "Payroll Run",
        "type": "text",
        "options": [],
        "example": "PAYRUN-2026-08",
        "description": ""
      },
      {
        "name": "Employee",
        "type": "text",
        "options": [],
        "example": "Rohit Menon",
        "description": ""
      },
      {
        "name": "Employee ID",
        "type": "text",
        "options": [],
        "example": "EMP-0114",
        "description": ""
      },
      {
        "name": "Department",
        "type": "select",
        "options": [
          "Sales",
          "Purchase",
          "Accounts",
          "Payroll",
          "Admin",
          "Finance",
          "Operations"
        ],
        "example": "Operations",
        "description": ""
      },
      {
        "name": "Period Start",
        "type": "date",
        "options": [],
        "example": "2026-08-01",
        "description": ""
      },
      {
        "name": "Period End",
        "type": "date",
        "options": [],
        "example": "2026-08-31",
        "description": ""
      },
      {
        "name": "Attendance Days",
        "type": "number",
        "options": [],
        "example": "26",
        "description": ""
      },
      {
        "name": "Paid Days",
        "type": "number",
        "options": [],
        "example": "26",
        "description": ""
      },
      {
        "name": "Gross Salary/Wages",
        "type": "currency",
        "options": [],
        "example": "96000.00",
        "description": ""
      },
      {
        "name": "Allowances",
        "type": "currency",
        "options": [],
        "example": "8400.00",
        "description": ""
      },
      {
        "name": "Deductions",
        "type": "currency",
        "options": [],
        "example": "1600.00",
        "description": ""
      },
      {
        "name": "TDS",
        "type": "currency",
        "options": [],
        "example": "3600.00",
        "description": ""
      },
      {
        "name": "SSF/PF Contribution",
        "type": "currency",
        "options": [],
        "example": "7680.00",
        "description": ""
      },
      {
        "name": "Other Deductions",
        "type": "currency",
        "options": [],
        "example": "500.00",
        "description": ""
      },
      {
        "name": "Net Salary/Wages",
        "type": "currency",
        "options": [],
        "example": "91020.00",
        "description": ""
      },
      {
        "name": "Payment Date",
        "type": "date",
        "options": [],
        "example": "2026-08-28",
        "description": ""
      },
      {
        "name": "Payment Mode",
        "type": "select",
        "options": [
          "Bank Transfer",
          "Cash",
          "Cheque",
          "Digital Payment"
        ],
        "example": "Bank Transfer",
        "description": ""
      },
      {
        "name": "Ledger Account",
        "type": "text",
        "options": [],
        "example": "Salaries & Wages",
        "description": ""
      },
      {
        "name": "Approval Reference",
        "type": "text",
        "options": [],
        "example": "APR-PR-2026-08",
        "description": ""
      },
      {
        "name": "Payroll Liability Balance",
        "type": "currency",
        "options": [],
        "example": "7680.00",
        "description": ""
      },
      {
        "name": "Statutory Reconciliation Status",
        "type": "select",
        "options": [
          "Reconciled",
          "Pending",
          "Variance"
        ],
        "example": "Pending",
        "description": ""
      },
      {
        "name": "Source Document",
        "type": "relation",
        "options": [],
        "example": "DOC-2026-0470",
        "description": ""
      },
      {
        "name": "Prepared By",
        "type": "text",
        "options": [],
        "example": "Sneha Iyer",
        "description": ""
      },
      {
        "name": "Reviewed By",
        "type": "text",
        "options": [],
        "example": "Ananya Rao",
        "description": ""
      },
      {
        "name": "Status",
        "type": "select",
        "options": [
          "Not started",
          "In progress",
          "Blocked",
          "Done",
          "Cancelled"
        ],
        "example": "In progress",
        "description": ""
      },
      {
        "name": "Notes",
        "type": "long_text",
        "options": [],
        "example": "Deductions of 1600.00 and other deductions of 500.00 total 2100.00; PF contribution carried as a liability until deposited.",
        "description": ""
      },
      {
        "name": "Salary Record ID",
        "type": "id",
        "options": [],
        "example": "",
        "description": ""
      }
    ],
    "example": [
      "PAYRUN-2026-08",
      "Rohit Menon",
      "EMP-0114",
      "Operations",
      "2026-08-01",
      "2026-08-31",
      "26",
      "26",
      "96000.00",
      "8400.00",
      "1600.00",
      "3600.00",
      "7680.00",
      "500.00",
      "91020.00",
      "2026-08-28",
      "Bank Transfer",
      "Salaries & Wages",
      "APR-PR-2026-08",
      "7680.00",
      "Pending",
      "DOC-2026-0470",
      "Sneha Iyer",
      "Ananya Rao",
      "In progress",
      "Deductions of 1600.00 and other deductions of 500.00 total 2100.00; PF contribution carried as a liability until deposited.",
      ""
    ],
    "optionsSheet": "Options",
    "referenceSheet": "Field Reference",
    "infoSheet": "About",
    "dataSheet": "Salary & Wage Accounting",
    "generated": [
      "Salary & Wage Accounting",
      "Options",
      "Field Reference",
      "About"
    ],
    "dataRows": 500,
    "rowEntity": "",
    "lastReviewed": "2026-09-26",
    "source": "SME Ops System Builder",
    "limitations": [
      "Empty template only. It does not calculate payroll, compute TDS or PF, or pay anyone.",
      "It does not file statutory returns or make deposits, and it gives no payroll or tax advice.",
      "Payroll calculation and statutory filing stay with a qualified person. This only holds the",
      "record of what they decided.",
      "It never holds real salary or employee data. Anyone who needs that uses the payroll system.",
      "Notion relations need both databases imported before the link column resolves."
    ]
  };

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Rebuild from module spec', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template rebuilt: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Drops the generated tabs so a rebuild starts from a clean set. */
function resetSheets(ss) {
  CONFIG.generated.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) ss.deleteSheet(sheet);
  });
}

/** A tab, cleared and ready. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  sheet.clear();
  return sheet;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : value);
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(sheet, column, optionsSheetName) {
  var options = ss.getSheetByName(optionsSheetName);
  if (!options) return;
  var last = options.getLastRow();
  if (last < 2) return;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, column, last - 1, column), true)
    .setAllowInvalid(false)
    .setHelpText('Pick a value from the list.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [o]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds every tab. Safe to run again. */
function build(ss) {
  resetSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(data, column, CONFIG.optionsSheet);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  // the example row, so the shape is obvious before anyone types
  if (CONFIG.example && CONFIG.example.length === names.length) {
    data.getRange(2, 1, 1, names.length).setValues([CONFIG.example]);
    data.getRange(2, 1, 1, names.length).setFontColor('#666666');
  }

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
