/**
 * Accounting Software Selection - Google Sheets template.
 *
 * Generated by tools/appsscript.py from the module field reference.
 * Edit the SKILL.md, not this file: the next run would overwrite your change.
 *
 * How to use
 *   1. Extensions > Apps Script, in the spreadsheet you want to build into.
 *   2. Paste this file over anything in the editor and save.
 *   3. Run buildIntoActive from the editor once, or use the "Build template"
 *      menu that appears on the sheet. main() creates a new spreadsheet
 *      instead, if you would rather not bind this script to one.
 *
 * Rebuilding clears the generated tabs and rewrites them, so it is safe to
 * run again after changing the spec. Real rows you have typed into the data
 * tab are kept; only the template structure is rewritten.
 */
var CONFIG = {
    "title": "Accounting Software Selection",
    "tier": "Growth",
    "layer": "Layer 1: Foundation",
    "fields": [
      {
        "name": "Evaluation ID",
        "type": "text",
        "options": [],
        "example": "EVAL-2026-01",
        "description": ""
      },
      {
        "name": "Software",
        "type": "text",
        "options": [],
        "example": "Example Product",
        "description": ""
      },
      {
        "name": "Vendor",
        "type": "text",
        "options": [],
        "example": "Example Vendor",
        "description": ""
      },
      {
        "name": "Business Activities",
        "type": "long_text",
        "options": [],
        "example": "Trading and manufacturing with a small services arm",
        "description": ""
      },
      {
        "name": "Modules Needed",
        "type": "long_text",
        "options": [],
        "example": "Accounting; inventory; manufacturing; VAT; TDS; payroll",
        "description": ""
      },
      {
        "name": "Deployment Type",
        "type": "select",
        "options": [
          "Cloud",
          "On-premise",
          "Hybrid"
        ],
        "example": "Cloud",
        "description": ""
      },
      {
        "name": "Accounting Coverage",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "5 Comprehensive",
        "description": ""
      },
      {
        "name": "Sales Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Purchase Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Inventory Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "5 Comprehensive",
        "description": ""
      },
      {
        "name": "Manufacturing Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "BOM Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Production/Work Order Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Production Costing",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Wastage/Scrap Tracking",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "2 Major limitations",
        "description": ""
      },
      {
        "name": "Batch/Lot Tracking",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "2 Major limitations",
        "description": ""
      },
      {
        "name": "Service Management",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "Untested",
        "description": ""
      },
      {
        "name": "VAT Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "TDS Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Payroll/SSF Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "IRD/Statutory Reporting",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "E-Billing/CBMS Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "Untested",
        "description": ""
      },
      {
        "name": "Financial Reporting",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Multi-Company Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "Not Required",
        "description": ""
      },
      {
        "name": "Branch Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "Not Required",
        "description": ""
      },
      {
        "name": "Warehouse Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "User Access Control",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Approval Workflow",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Data Backup & Security",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Migration Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "Integration/API",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "2 Major limitations",
        "description": ""
      },
      {
        "name": "Data Export",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "4 Strong",
        "description": ""
      },
      {
        "name": "After-Sales Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "2 Major limitations",
        "description": ""
      },
      {
        "name": "Implementation Support",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Training",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "3 Adequate",
        "description": ""
      },
      {
        "name": "Customization",
        "type": "select",
        "options": [
          "1 Missing",
          "2 Major limitations",
          "3 Adequate",
          "4 Strong",
          "5 Comprehensive",
          "Not Required",
          "Untested"
        ],
        "example": "2 Major limitations",
        "description": ""
      },
      {
        "name": "Reliability Rating",
        "type": "number",
        "options": [],
        "example": "4",
        "description": ""
      },
      {
        "name": "Ease of Use Rating",
        "type": "number",
        "options": [],
        "example": "4",
        "description": ""
      },
      {
        "name": "Support Quality Rating",
        "type": "number",
        "options": [],
        "example": "2",
        "description": ""
      },
      {
        "name": "Demo Date",
        "type": "date",
        "options": [],
        "example": "2026-07-18",
        "description": ""
      },
      {
        "name": "Demo Test Result",
        "type": "select",
        "options": [
          "Not Tested",
          "Partially Passed",
          "Passed",
          "Failed"
        ],
        "example": "Partially Passed",
        "description": ""
      },
      {
        "name": "Test Transactions Run",
        "type": "number",
        "options": [],
        "example": "25",
        "description": ""
      },
      {
        "name": "Licence Cost",
        "type": "currency",
        "options": [],
        "example": "480000.00",
        "description": ""
      },
      {
        "name": "Implementation Cost",
        "type": "currency",
        "options": [],
        "example": "120000.00",
        "description": ""
      },
      {
        "name": "Customization Cost",
        "type": "currency",
        "options": [],
        "example": "65000.00",
        "description": ""
      },
      {
        "name": "Training Cost",
        "type": "currency",
        "options": [],
        "example": "45000.00",
        "description": ""
      },
      {
        "name": "Annual Renewal",
        "type": "currency",
        "options": [],
        "example": "240000.00",
        "description": ""
      },
      {
        "name": "First-Year Cost",
        "type": "currency",
        "options": [],
        "example": "950000.00",
        "description": ""
      },
      {
        "name": "Three-Year TCO",
        "type": "currency",
        "options": [],
        "example": "1430000.00",
        "description": ""
      },
      {
        "name": "Evaluation Status",
        "type": "select",
        "options": [
          "Not Evaluated",
          "Demo Scheduled",
          "Demo Completed",
          "Testing",
          "Evaluated"
        ],
        "example": "Evaluated",
        "description": ""
      },
      {
        "name": "Deal-breaker",
        "type": "select",
        "options": [
          "Yes",
          "No"
        ],
        "example": "No",
        "description": ""
      },
      {
        "name": "Selection Decision",
        "type": "select",
        "options": [
          "Selected",
          "Shortlisted",
          "Not Selected",
          "Rejected"
        ],
        "example": "Not Selected",
        "description": ""
      },
      {
        "name": "Rejection Reason",
        "type": "select",
        "options": [
          "Cost",
          "Missing Capability",
          "Poor Fit",
          "Poor Support",
          "Implementation Risk",
          "Security Risk",
          "User Experience",
          "Other"
        ],
        "example": "Poor Support",
        "description": ""
      },
      {
        "name": "Evaluated By",
        "type": "text",
        "options": [],
        "example": "Example Evaluator",
        "description": ""
      },
      {
        "name": "Evidence/Source",
        "type": "text",
        "options": [],
        "example": "Vendor demo 2026-07-18; 25 test transactions; written quotation",
        "description": ""
      },
      {
        "name": "Notes",
        "type": "long_text",
        "options": [],
        "example": "Not selected on local support response time; revisit if the reseller adds a local office. Service and e-billing modules still untested.",
        "description": ""
      },
      {
        "name": "Selection ID",
        "type": "id",
        "options": [],
        "example": "",
        "description": ""
      }
    ],
    "example": [
      "EVAL-2026-01",
      "Example Product",
      "Example Vendor",
      "Trading and manufacturing with a small services arm",
      "Accounting; inventory; manufacturing; VAT; TDS; payroll",
      "Cloud",
      "5 Comprehensive",
      "4 Strong",
      "4 Strong",
      "5 Comprehensive",
      "4 Strong",
      "4 Strong",
      "3 Adequate",
      "3 Adequate",
      "2 Major limitations",
      "2 Major limitations",
      "Untested",
      "4 Strong",
      "3 Adequate",
      "3 Adequate",
      "3 Adequate",
      "Untested",
      "4 Strong",
      "Not Required",
      "Not Required",
      "4 Strong",
      "4 Strong",
      "3 Adequate",
      "4 Strong",
      "4 Strong",
      "2 Major limitations",
      "4 Strong",
      "2 Major limitations",
      "3 Adequate",
      "3 Adequate",
      "2 Major limitations",
      "4",
      "4",
      "2",
      "2026-07-18",
      "Partially Passed",
      "25",
      "480000.00",
      "120000.00",
      "65000.00",
      "45000.00",
      "240000.00",
      "950000.00",
      "1430000.00",
      "Evaluated",
      "No",
      "Not Selected",
      "Poor Support",
      "Example Evaluator",
      "Vendor demo 2026-07-18; 25 test transactions; written quotation",
      "Not selected on local support response time; revisit if the reseller adds a local office. Service and e-billing modules still untested.",
      ""
    ],
    "optionsSheet": "Options",
    "referenceSheet": "Field Reference",
    "infoSheet": "About",
    "dataSheet": "Accounting Software Selection",
    "generated": [
      "Accounting Software Selection",
      "Options",
      "Field Reference",
      "About"
    ],
    "dataRows": 500,
    "rowEntity": "",
    "lastReviewed": "2026-09-26",
    "source": "SME Ops System Builder",
    "limitations": [
      "Empty template only. It does not score for you, run the demos, verify a vendor's claims or turn a quotation into a TCO.",
      "It never selects the package. It records the decision the business makes in Selection Decision, with the reason and the deal-breaker flag beside it; it does not make the decision.",
      "Not a bookkeeping, tax-filing, legal or procurement system. Quotations, contracts and purchase orders stay in the vendor's own process.",
      "It cannot verify Nepal IRD, VAT, TDS, e-billing, CBMS or SSF handling for you. Those stay Untested until the business holds current evidence from the vendor or the authority.",
      "A go-live checklist is a list the business carries out with the vendor. Chart of accounts, tax configuration, users, inventory, opening balances and the test entry are not done by this skill.",
      "Notion relations need both databases imported before the link column resolves."
    ]
  };

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Rebuild from module spec', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template rebuilt: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Drops the generated tabs so a rebuild starts from a clean set. */
function resetSheets(ss) {
  CONFIG.generated.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) ss.deleteSheet(sheet);
  });
}

/** A tab, cleared and ready. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  sheet.clear();
  return sheet;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : value);
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(sheet, column, optionsSheetName) {
  var options = ss.getSheetByName(optionsSheetName);
  if (!options) return;
  var last = options.getLastRow();
  if (last < 2) return;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, column, last - 1, column), true)
    .setAllowInvalid(false)
    .setHelpText('Pick a value from the list.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [o]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds every tab. Safe to run again. */
function build(ss) {
  resetSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(data, column, CONFIG.optionsSheet);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  // the example row, so the shape is obvious before anyone types
  if (CONFIG.example && CONFIG.example.length === names.length) {
    data.getRange(2, 1, 1, names.length).setValues([CONFIG.example]);
    data.getRange(2, 1, 1, names.length).setFontColor('#666666');
  }

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
