/**
 * Inventory / Stock Reconciliation - Google Sheets template.
 *
 * Generated by tools/appsscript.py from the module field reference.
 * Edit the SKILL.md, not this file: the next run would overwrite your change.
 *
 * How to use
 *   1. Extensions > Apps Script, in the spreadsheet you want to build into.
 *   2. Paste this file over anything in the editor and save.
 *   3. Run buildIntoActive from the editor once, or use the "Build template"
 *      menu that appears on the sheet. main() creates a new spreadsheet
 *      instead, if you would rather not bind this script to one.
 *
 * Rebuilding clears the generated tabs and rewrites them, so it is safe to
 * run again after changing the spec. Real rows you have typed into the data
 * tab are kept; only the template structure is rewritten.
 */
var CONFIG = {
    "title": "Inventory / Stock Reconciliation",
    "tier": "Growth",
    "layer": "Layer 7: Reconcile",
    "fields": [
      {
        "name": "Reconciliation Number",
        "type": "text",
        "options": [],
        "example": "STK-2026-0031",
        "description": ""
      },
      {
        "name": "Count Date",
        "type": "date",
        "options": [],
        "example": "2026-08-29",
        "description": ""
      },
      {
        "name": "Item Code",
        "type": "text",
        "options": [],
        "example": "ITM-0455",
        "description": ""
      },
      {
        "name": "Item Name",
        "type": "text",
        "options": [],
        "example": "Corrugated carton, 3 ply, 24x18x12",
        "description": ""
      },
      {
        "name": "Category",
        "type": "select",
        "options": [
          "Raw Material",
          "Work In Progress",
          "Finished Goods",
          "Consumable",
          "Packaging",
          "Spare",
          "Other"
        ],
        "example": "Packaging",
        "description": ""
      },
      {
        "name": "UOM",
        "type": "select",
        "options": [
          "Nos",
          "Kg",
          "Litre",
          "Metre",
          "Set",
          "Hour",
          "Box",
          "Packet"
        ],
        "example": "Nos",
        "description": ""
      },
      {
        "name": "Location/Warehouse",
        "type": "text",
        "options": [],
        "example": "Main Store",
        "description": ""
      },
      {
        "name": "Book Quantity",
        "type": "number",
        "options": [],
        "example": "1240",
        "description": ""
      },
      {
        "name": "Physical Quantity",
        "type": "number",
        "options": [],
        "example": "1218",
        "description": ""
      },
      {
        "name": "Variance Quantity",
        "type": "number",
        "options": [],
        "example": "-22",
        "description": ""
      },
      {
        "name": "Unit Rate",
        "type": "currency",
        "options": [],
        "example": "169.00",
        "description": ""
      },
      {
        "name": "Variance Value",
        "type": "currency",
        "options": [],
        "example": "-3718.00",
        "description": ""
      },
      {
        "name": "Variance Reason",
        "type": "select",
        "options": [
          "Shortage",
          "Excess",
          "Damage",
          "Expiry",
          "Slow Moving",
          "Unrecorded Purchase",
          "Unrecorded Issue",
          "Data Entry Error",
          "Under Investigation"
        ],
        "example": "Unrecorded Issue",
        "description": ""
      },
      {
        "name": "Damaged Quantity",
        "type": "number",
        "options": [],
        "example": "12",
        "description": ""
      },
      {
        "name": "Expired Quantity",
        "type": "number",
        "options": [],
        "example": "2",
        "description": ""
      },
      {
        "name": "Slow Moving Flag",
        "type": "select",
        "options": [
          "Yes",
          "No"
        ],
        "example": "No",
        "description": ""
      },
      {
        "name": "Unrecorded Purchases",
        "type": "number",
        "options": [],
        "example": "1",
        "description": ""
      },
      {
        "name": "Unrecorded Issues",
        "type": "number",
        "options": [],
        "example": "8",
        "description": ""
      },
      {
        "name": "Investigation Notes",
        "type": "long_text",
        "options": [],
        "example": "Shortfall of 22 units: 12 damaged and 2 expired units written off at the count, 8 units issued on two dispatches with no stock entry; raised with the warehouse and booked.",
        "description": ""
      },
      {
        "name": "Adjustment Entry",
        "type": "text",
        "options": [],
        "example": "ADJ-STK-2026-0031",
        "description": ""
      },
      {
        "name": "Adjustment Date",
        "type": "date",
        "options": [],
        "example": "2026-08-30",
        "description": ""
      },
      {
        "name": "Approved By",
        "type": "text",
        "options": [],
        "example": "Vikram Singh",
        "description": ""
      },
      {
        "name": "Counted By",
        "type": "text",
        "options": [],
        "example": "Rohit Menon",
        "description": ""
      },
      {
        "name": "Verified By",
        "type": "text",
        "options": [],
        "example": "Sneha Iyer",
        "description": ""
      },
      {
        "name": "Count Frequency",
        "type": "select",
        "options": [
          "Monthly",
          "Quarterly",
          "Half-Yearly",
          "Annual"
        ],
        "example": "Monthly",
        "description": ""
      },
      {
        "name": "Status",
        "type": "select",
        "options": [
          "Not started",
          "In progress",
          "Blocked",
          "Done",
          "Cancelled"
        ],
        "example": "In progress",
        "description": ""
      },
      {
        "name": "Notes",
        "type": "long_text",
        "options": [],
        "example": "Count sheet filed with the reconciliation record.",
        "description": ""
      },
      {
        "name": "Inventory Reconciliation ID",
        "type": "id",
        "options": [],
        "example": "",
        "description": ""
      }
    ],
    "example": [
      "STK-2026-0031",
      "2026-08-29",
      "ITM-0455",
      "Corrugated carton, 3 ply, 24x18x12",
      "Packaging",
      "Nos",
      "Main Store",
      "1240",
      "1218",
      "-22",
      "169.00",
      "-3718.00",
      "Unrecorded Issue",
      "12",
      "2",
      "No",
      "1",
      "8",
      "Shortfall of 22 units: 12 damaged and 2 expired units written off at the count, 8 units issued on two dispatches with no stock entry; raised with the warehouse and booked.",
      "ADJ-STK-2026-0031",
      "2026-08-30",
      "Vikram Singh",
      "Rohit Menon",
      "Sneha Iyer",
      "Monthly",
      "In progress",
      "Count sheet filed with the reconciliation record.",
      ""
    ],
    "optionsSheet": "Options",
    "referenceSheet": "Field Reference",
    "infoSheet": "About",
    "dataSheet": "Inventory - Stock Reconciliation",
    "generated": [
      "Inventory - Stock Reconciliation",
      "Options",
      "Field Reference",
      "About"
    ],
    "dataRows": 500,
    "rowEntity": "",
    "lastReviewed": "2026-09-26",
    "source": "SME Ops System Builder",
    "limitations": [
      "Empty template only. It does not count stock, value inventory, or post journal entries.",
      "The variance arithmetic can be done by hand or by the accounting package. What this",
      "records is the count, the difference and the authorisation - not the conclusion about",
      "what caused the shrinkage.",
      "It cannot tell theft from a mis-pick from an unrecorded issue. That determination is",
      "made by a person who knows the operation, and this record only carries the reason they"
    ]
  };

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Rebuild from module spec', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template rebuilt: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Drops the generated tabs so a rebuild starts from a clean set. */
function resetSheets(ss) {
  CONFIG.generated.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) ss.deleteSheet(sheet);
  });
}

/** A tab, cleared and ready. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  sheet.clear();
  return sheet;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : value);
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(sheet, column, optionsSheetName) {
  var options = ss.getSheetByName(optionsSheetName);
  if (!options) return;
  var last = options.getLastRow();
  if (last < 2) return;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, column, last - 1, column), true)
    .setAllowInvalid(false)
    .setHelpText('Pick a value from the list.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [o]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds every tab. Safe to run again. */
function build(ss) {
  resetSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(data, column, CONFIG.optionsSheet);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  // the example row, so the shape is obvious before anyone types
  if (CONFIG.example && CONFIG.example.length === names.length) {
    data.getRange(2, 1, 1, names.length).setValues([CONFIG.example]);
    data.getRange(2, 1, 1, names.length).setFontColor('#666666');
  }

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
