/**
 * Petty Cash Management - Google Sheets template.
 *
 * Generated by tools/appsscript.py from the module field reference.
 * Edit the SKILL.md, not this file: the next run would overwrite your change.
 *
 * How to use
 *   1. Extensions > Apps Script, in the spreadsheet you want to build into.
 *   2. Paste this file over anything in the editor and save.
 *   3. Run buildIntoActive from the editor once, or use the "Build template"
 *      menu that appears on the sheet. main() creates a new spreadsheet
 *      instead, if you would rather not bind this script to one.
 *
 * Rebuilding clears the generated tabs and rewrites them, so it is safe to
 * run again after changing the spec. Real rows you have typed into the data
 * tab are kept; only the template structure is rewritten.
 */
var CONFIG = {
    "title": "Petty Cash Management",
    "tier": "Starter",
    "layer": "Layer 4: Cash",
    "fields": [
      {
        "name": "Entry Number",
        "type": "text",
        "options": [],
        "example": "PC-2026-0188",
        "description": ""
      },
      {
        "name": "Entry Date",
        "type": "date",
        "options": [],
        "example": "2026-08-31",
        "description": ""
      },
      {
        "name": "Entry Type",
        "type": "select",
        "options": [
          "Payment",
          "Replenishment",
          "Receipt",
          "Count"
        ],
        "example": "Count",
        "description": ""
      },
      {
        "name": "Payee",
        "type": "text",
        "options": [],
        "example": "Several payees",
        "description": ""
      },
      {
        "name": "Purpose",
        "type": "text",
        "options": [],
        "example": "Courier and postage paid from the float during August",
        "description": ""
      },
      {
        "name": "Cash Out",
        "type": "currency",
        "options": [],
        "example": "7250.00",
        "description": ""
      },
      {
        "name": "Cash In",
        "type": "currency",
        "options": [],
        "example": "7000.00",
        "description": ""
      },
      {
        "name": "Running Cash Balance",
        "type": "currency",
        "options": [],
        "example": "2250.00",
        "description": ""
      },
      {
        "name": "Cash Limit",
        "type": "currency",
        "options": [],
        "example": "10000.00",
        "description": ""
      },
      {
        "name": "Within Limit",
        "type": "select",
        "options": [
          "Yes",
          "No"
        ],
        "example": "Yes",
        "description": ""
      },
      {
        "name": "Custodian",
        "type": "text",
        "options": [],
        "example": "Rohit Menon",
        "description": ""
      },
      {
        "name": "Supporting Document",
        "type": "select",
        "options": [
          "Bill/Invoice",
          "Receipt Note",
          "Wage Sheet",
          "Rent Record",
          "Payment Voucher",
          "Other"
        ],
        "example": "Bill/Invoice",
        "description": ""
      },
      {
        "name": "Document Reference",
        "type": "text",
        "options": [],
        "example": "BILL-4471",
        "description": ""
      },
      {
        "name": "Voucher Number",
        "type": "text",
        "options": [],
        "example": "VCH-2026-1044",
        "description": ""
      },
      {
        "name": "Approved By",
        "type": "text",
        "options": [],
        "example": "Ananya Rao",
        "description": ""
      },
      {
        "name": "Physical Count Date",
        "type": "date",
        "options": [],
        "example": "2026-08-31",
        "description": ""
      },
      {
        "name": "Physical Count",
        "type": "currency",
        "options": [],
        "example": "2100.00",
        "description": ""
      },
      {
        "name": "Count Variance",
        "type": "currency",
        "options": [],
        "example": "150.00",
        "description": ""
      },
      {
        "name": "Variance Status",
        "type": "select",
        "options": [
          "Not counted",
          "Matched",
          "Short",
          "Over",
          "Under Investigation"
        ],
        "example": "Short",
        "description": ""
      },
      {
        "name": "Investigation Notes",
        "type": "long_text",
        "options": [],
        "example": "Count 150.00 short of the register; a courier bill of that amount may have been entered but not paid. Under investigation with the approver.",
        "description": ""
      },
      {
        "name": "Ledger Account",
        "type": "text",
        "options": [],
        "example": "Petty Cash",
        "description": ""
      },
      {
        "name": "Entry Verified",
        "type": "select",
        "options": [
          "Not started",
          "In progress",
          "Blocked",
          "Done",
          "Cancelled"
        ],
        "example": "In progress",
        "description": ""
      },
      {
        "name": "Notes",
        "type": "long_text",
        "options": [],
        "example": "Count sheet CNT-2026-08-31 signed by custodian and approver; replenishment drawn from bank on 01 Aug.",
        "description": ""
      },
      {
        "name": "Petty Cash ID",
        "type": "id",
        "options": [],
        "example": "",
        "description": ""
      }
    ],
    "example": [
      "PC-2026-0188",
      "2026-08-31",
      "Count",
      "Several payees",
      "Courier and postage paid from the float during August",
      "7250.00",
      "7000.00",
      "2250.00",
      "10000.00",
      "Yes",
      "Rohit Menon",
      "Bill/Invoice",
      "BILL-4471",
      "VCH-2026-1044",
      "Ananya Rao",
      "2026-08-31",
      "2100.00",
      "150.00",
      "Short",
      "Count 150.00 short of the register; a courier bill of that amount may have been entered but not paid. Under investigation with the approver.",
      "Petty Cash",
      "In progress",
      "Count sheet CNT-2026-08-31 signed by custodian and approver; replenishment drawn from bank on 01 Aug.",
      ""
    ],
    "optionsSheet": "Options",
    "referenceSheet": "Field Reference",
    "infoSheet": "About",
    "dataSheet": "Petty Cash Management",
    "generated": [
      "Petty Cash Management",
      "Options",
      "Field Reference",
      "About"
    ],
    "dataRows": 500,
    "rowEntity": "",
    "lastReviewed": "2026-09-26",
    "source": "SME Ops System Builder",
    "limitations": [
      "Empty template only. It does not hold, disburse or approve cash, and it does not connect",
      "to a till or a bank.",
      "The count is periodic by design, not optional. A register with no count is a diary, and",
      "the day the count is skipped is the day a shortage becomes invisible.",
      "The count fields stay empty until the count happens; `Variance Status` is what carries the",
      "state in the meantime. Do not fill a count in advance to make the row look complete."
    ]
  };

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Rebuild from module spec', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template rebuilt: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Drops the generated tabs so a rebuild starts from a clean set. */
function resetSheets(ss) {
  CONFIG.generated.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) ss.deleteSheet(sheet);
  });
}

/** A tab, cleared and ready. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  sheet.clear();
  return sheet;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : value);
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(sheet, column, optionsSheetName) {
  var options = ss.getSheetByName(optionsSheetName);
  if (!options) return;
  var last = options.getLastRow();
  if (last < 2) return;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, column, last - 1, column), true)
    .setAllowInvalid(false)
    .setHelpText('Pick a value from the list.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [o]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds every tab. Safe to run again. */
function build(ss) {
  resetSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(data, column, CONFIG.optionsSheet);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  // the example row, so the shape is obvious before anyone types
  if (CONFIG.example && CONFIG.example.length === names.length) {
    data.getRange(2, 1, 1, names.length).setValues([CONFIG.example]);
    data.getRange(2, 1, 1, names.length).setFontColor('#666666');
  }

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
