/**
 * Receipt Accounting - Google Sheets template.
 *
 * Generated by tools/appsscript.py from the module field reference.
 * Edit the SKILL.md, not this file: the next run would overwrite your change.
 *
 * How to use
 *   1. Extensions > Apps Script, in the spreadsheet you want to build into.
 *   2. Paste this file over anything in the editor and save.
 *   3. Run buildIntoActive from the editor once, or use the "Build template"
 *      menu that appears on the sheet. main() creates a new spreadsheet
 *      instead, if you would rather not bind this script to one.
 *
 * Rebuilding clears the generated tabs and rewrites them, so it is safe to
 * run again after changing the spec. Real rows you have typed into the data
 * tab are kept; only the template structure is rewritten.
 */
var CONFIG = {
    "title": "Receipt Accounting",
    "tier": "Starter",
    "layer": "Layer 3: Record",
    "fields": [
      {
        "name": "Receipt Number",
        "type": "text",
        "options": [],
        "example": "RCP-2026-0312",
        "description": ""
      },
      {
        "name": "Receipt Date",
        "type": "date",
        "options": [],
        "example": "2026-08-19",
        "description": ""
      },
      {
        "name": "Received From",
        "type": "text",
        "options": [],
        "example": "Greyson Foods",
        "description": ""
      },
      {
        "name": "Receipt Mode",
        "type": "select",
        "options": [
          "Cash",
          "Bank",
          "Cheque",
          "Fonepay/QR",
          "Other Digital Payment"
        ],
        "example": "Bank",
        "description": ""
      },
      {
        "name": "Cash/Bank Account",
        "type": "text",
        "options": [],
        "example": "HDFC Current ****0042",
        "description": ""
      },
      {
        "name": "Reference (Cheque/UTR/ID)",
        "type": "text",
        "options": [],
        "example": "UTR-2026-0819",
        "description": ""
      },
      {
        "name": "Gross Amount Received",
        "type": "currency",
        "options": [],
        "example": "140000.00",
        "description": ""
      },
      {
        "name": "Receipt Type",
        "type": "select",
        "options": [
          "Sale Collection",
          "Receivable Collection",
          "Advance from Customer",
          "Loan Received",
          "Capital Contribution",
          "Other"
        ],
        "example": "Receivable Collection",
        "description": ""
      },
      {
        "name": "Treats as Sale Income",
        "type": "select",
        "options": [
          "Yes",
          "No"
        ],
        "example": "No",
        "description": ""
      },
      {
        "name": "Sales Invoice Allocated",
        "type": "relation",
        "options": [],
        "example": "SAL-2026-0033",
        "description": ""
      },
      {
        "name": "Amount Allocated",
        "type": "currency",
        "options": [],
        "example": "130712.40",
        "description": ""
      },
      {
        "name": "Unapplied Amount",
        "type": "currency",
        "options": [],
        "example": "9287.60",
        "description": ""
      },
      {
        "name": "Adjust Against",
        "type": "text",
        "options": [],
        "example": "Customer Advance - Greyson Foods",
        "description": ""
      },
      {
        "name": "TDS Collected on Receipt",
        "type": "currency",
        "options": [],
        "example": "1307.12",
        "description": ""
      },
      {
        "name": "Voucher Number",
        "type": "text",
        "options": [],
        "example": "VCH-2026-1027",
        "description": ""
      },
      {
        "name": "Ledger Account",
        "type": "text",
        "options": [],
        "example": "Bank - HDFC Current",
        "description": ""
      },
      {
        "name": "Source Document",
        "type": "relation",
        "options": [],
        "example": "DOC-2026-0461",
        "description": ""
      },
      {
        "name": "Reconciliation Status",
        "type": "select",
        "options": [
          "Unreconciled",
          "Reconciled",
          "Difference"
        ],
        "example": "Unreconciled",
        "description": ""
      },
      {
        "name": "Prepared By",
        "type": "text",
        "options": [],
        "example": "Ananya Rao",
        "description": ""
      },
      {
        "name": "Verified By",
        "type": "text",
        "options": [],
        "example": "Sneha Iyer",
        "description": ""
      },
      {
        "name": "Entry Verified",
        "type": "select",
        "options": [
          "Not started",
          "In progress",
          "Blocked",
          "Done",
          "Cancelled"
        ],
        "example": "In progress",
        "description": ""
      },
      {
        "name": "Notes",
        "type": "long_text",
        "options": [],
        "example": "Part collected against INV-2026-0733; TDS of 1307.12 remitted from this receipt; balance held as advance, not income.",
        "description": ""
      },
      {
        "name": "Receipt ID",
        "type": "id",
        "options": [],
        "example": "",
        "description": ""
      }
    ],
    "example": [
      "RCP-2026-0312",
      "2026-08-19",
      "Greyson Foods",
      "Bank",
      "HDFC Current ****0042",
      "UTR-2026-0819",
      "140000.00",
      "Receivable Collection",
      "No",
      "SAL-2026-0033",
      "130712.40",
      "9287.60",
      "Customer Advance - Greyson Foods",
      "1307.12",
      "VCH-2026-1027",
      "Bank - HDFC Current",
      "DOC-2026-0461",
      "Unreconciled",
      "Ananya Rao",
      "Sneha Iyer",
      "In progress",
      "Part collected against INV-2026-0733; TDS of 1307.12 remitted from this receipt; balance held as advance, not income.",
      ""
    ],
    "optionsSheet": "Options",
    "referenceSheet": "Field Reference",
    "infoSheet": "About",
    "dataSheet": "Receipt Accounting",
    "generated": [
      "Receipt Accounting",
      "Options",
      "Field Reference",
      "About"
    ],
    "dataRows": 500,
    "rowEntity": "",
    "lastReviewed": "2026-09-26",
    "source": "SME Ops System Builder",
    "limitations": [
      "Empty template only. It does not post entries, raise invoices or compute tax.",
      "The type fields do not decide the accounting treatment for you. The ledger, the tax",
      "position and the period all matter, and a qualified accountant confirms that.",
      "Unapplied amounts need a follow-up process. This table records them; it does not chase",
      "them.",
      "Notion relations need both databases imported before the link column resolves."
    ]
  };

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Rebuild from module spec', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template rebuilt: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Drops the generated tabs so a rebuild starts from a clean set. */
function resetSheets(ss) {
  CONFIG.generated.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) ss.deleteSheet(sheet);
  });
}

/** A tab, cleared and ready. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  sheet.clear();
  return sheet;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : value);
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(sheet, column, optionsSheetName) {
  var options = ss.getSheetByName(optionsSheetName);
  if (!options) return;
  var last = options.getLastRow();
  if (last < 2) return;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, column, last - 1, column), true)
    .setAllowInvalid(false)
    .setHelpText('Pick a value from the list.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [o]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds every tab. Safe to run again. */
function build(ss) {
  resetSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(data, column, CONFIG.optionsSheet);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  // the example row, so the shape is obvious before anyone types
  if (CONFIG.example && CONFIG.example.length === names.length) {
    data.getRange(2, 1, 1, names.length).setValues([CONFIG.example]);
    data.getRange(2, 1, 1, names.length).setFontColor('#666666');
  }

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
